using System.Text.Json.Serialization;

namespace Api.Accounts;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(RegisterRequest))]
[JsonSerializable(typeof(RegisterResponse))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(GoogleAuthRequest))]
[JsonSerializable(typeof(GoogleAuthResponse))]
[JsonSerializable(typeof(RefreshTokenRequest))]
[JsonSerializable(typeof(RefreshTokenResponse))]
[JsonSerializable(typeof(SubmitProfessionalCredentialRequest))]
[JsonSerializable(typeof(SubmitProfessionalCredentialResponse))]
[JsonSerializable(typeof(ProfessionalVerificationDecisionRequest))]
[JsonSerializable(typeof(ProfessionalVerificationDecisionResponse))]
[JsonSerializable(typeof(IReadOnlyList<ProfessionalVerificationQueueEntry>))]
[JsonSerializable(typeof(BeginTotpEnrollmentRequest))]
[JsonSerializable(typeof(BeginTotpEnrollmentResponse))]
[JsonSerializable(typeof(ConfirmTotpEnrollmentRequest))]
[JsonSerializable(typeof(ConfirmTotpEnrollmentResponse))]
[JsonSerializable(typeof(TotpChallengeRequest))]
[JsonSerializable(typeof(CreatePairingSessionRequest))]
[JsonSerializable(typeof(CreatePairingSessionResponse))]
[JsonSerializable(typeof(ClaimPairingSessionRequest))]
[JsonSerializable(typeof(ClaimPairingSessionResponse))]
[JsonSerializable(typeof(PairingClaimStatusResponse))]
[JsonSerializable(typeof(SubmitPairingPayloadRequest))]
[JsonSerializable(typeof(PairingSessionPayloadResponse))]
[JsonSerializable(typeof(MagicLinkRequestRequest))]
[JsonSerializable(typeof(MagicLinkRequestResponse))]
[JsonSerializable(typeof(VerifyMagicLinkRequest))]
[JsonSerializable(typeof(VerifyMagicLinkResponse))]
[JsonSerializable(typeof(CompleteMagicLinkWebAuthnRequest))]
[JsonSerializable(typeof(CompleteMagicLinkWebAuthnResponse))]
[JsonSerializable(typeof(MagicLinkDebugLastResponse))]
[JsonSerializable(typeof(RecoverAccessRequest))]
[JsonSerializable(typeof(RecoverAccessResponse))]
[JsonSerializable(typeof(RegisterRecoveryVerifierRequest))]
[JsonSerializable(typeof(RegisterRecoveryVerifierResponse))]
public partial class AccountsJsonContext : JsonSerializerContext
{
}
