app = "TODO-preencher-apos-fly-launch"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "--migrate-only"
  release_command_timeout = "5m"

[http_service]
  internal_port = 8080
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  timeout = "5s"
  method = "GET"
  path = "/health"
  protocol = "http"

[[vm]]
  size = "shared-cpu-1x"
